function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 30-Jul-2023 19:39:10

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot1 = plot(X1,Y1,'Parent',axes1,'LineWidth',2);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,62.92,51.016);
% Create datatip
datatip(plot1,'DataIndex',12584,'Location','southeast');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,119.98,66.7363);
% Create datatip
datatip(plot1,'DataIndex',23996,'Location','southeast');

% Create ylabel
ylabel('Datarate (Mbps)');

% Create xlabel
xlabel('Time (in secs)');

% Create title
title('Sending rates for Host 1');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 150]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 100]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XGrid','on','XMinorTick','on','XTick',[0 10 40 50 100 120 150],...
    'YGrid','on','YMinorTick','on');
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.239382239382241 0.723404255319149 0.121621621621621 0.167173252279635]);
hold(axes2,'on');

% Create plot
plot2 = plot(X1,Y1,'Parent',axes2,'LineWidth',2);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot2,63.475,50.9066);
% Create datatip
datatip(plot2,'DataIndex',12695,'Location','southeast');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot2,119.98,66.7363);
% Create datatip
datatip(plot2,'DataIndex',23996,'Location','northeast');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot2,120.005,0);
% Create datatip
datatip(plot2,'DataIndex',24001);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[10 10.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[40 80]);
box(axes2,'on');
hold(axes2,'off');
% Create arrow
annotation(figure1,'arrow',[0.27027027027027 0.196911196911197],...
    [0.722404255319149 0.550151975683891]);

