function createfigure1(X1, YMatrix1)
%CREATEFIGURE1(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 30-Jul-2023 23:11:08

% Create figure
figure;

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','Host0','Marker','*');
set(plot1(2),'DisplayName','Host1',...
    'MarkerEdgeColor',[0.149019607843137 0.149019607843137 0.149019607843137],...
    'MarkerSize',5);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1(2),10.1760282516479,0.000833559199236333);
% Create datatip
datatip(plot1(2),'InterpolationFactor',0.205559683299427,'DataIndex',36,...
    'SnapToDataVertex','off',...
    'Location','northwest');

% Create ylabel
ylabel('Delay Bounds (secs)');

% Create xlabel
xlabel('Time (secs)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[10 10.1999998092651]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.0450000017881393]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.603412567556537 0.73935100932736 0.224126508604358 0.124472616971304]);

