//
// Generated file, do not edit! Created by opp_msgtool 6.0 from sdnmsg.msg.
//

#ifndef __SDNMSG_M_H
#define __SDNMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Sdm;
/**
 * Class generated from <tt>sdnmsg.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message Sdm
 * {
 *     //    int someField;
 *     //    string anotherField;
 *     double rates[];
 * 
 * }
 * </pre>
 */
class Sdm : public ::omnetpp::cMessage
{
  protected:
    double *rates = nullptr;
    size_t rates_arraysize = 0;

  private:
    void copy(const Sdm& other);

  protected:
    bool operator==(const Sdm&) = delete;

  public:
    Sdm(const char *name=nullptr, short kind=0);
    Sdm(const Sdm& other);
    virtual ~Sdm();
    Sdm& operator=(const Sdm& other);
    virtual Sdm *dup() const override {return new Sdm(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setRatesArraySize(size_t size);
    virtual size_t getRatesArraySize() const;
    virtual double getRates(size_t k) const;
    virtual void setRates(size_t k, double rates);
    virtual void insertRates(size_t k, double rates);
    [[deprecated]] void insertRates(double rates) {appendRates(rates);}
    virtual void appendRates(double rates);
    virtual void eraseRates(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Sdm& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Sdm& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Sdm *fromAnyPtr(any_ptr ptr) { return check_and_cast<Sdm*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SDNMSG_M_H

